# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WGSocketServer' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for WGSocketServer

  pod 'CocoaAsyncSocket'

  target 'WGSocketServerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WGSocketServerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
