# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WGSocketClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for WGSocketClient
  pod 'CocoaAsyncSocket'

  target 'WGSocketClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WGSocketClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
